# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        VERSION: 1.0.3
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION}
    - name: Push
      run: dotnet nuget push ${GITHUB_ACTION_PATH}/JwtAuthenticationPackage.${VERSION}.nupkg --source https://nuget.pkg.github.com/anavgil/index.json --api-key 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
