# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish NuGet (Private Nuget.Server)
      # You may pin to the exact commit or the version.
      # uses: rollycodes/publish-nuget-private@c67b9a113c5871124d37592cf95fb8e7a0cf1a37
      uses: rollycodes/publish-nuget-private@v3.0.1
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: /home/runner/work/BasicJWTAuthenticationPackage/BasicJWTAuthenticationPackage/JwtAuthenticationPackage/JwtAuthenticationPackage.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: JwtAuthenticationPackage
        # API key to authenticate with NuGet server
        NUGET_KEY: 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
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://nuget.pkg.github.com/anavgil
